# This file defines the configurable inputs for the soap erosion simulation.
# Users can edit this file to change the simulation setup, including:
# - Soap bar size
# - Voxel resolution (mm or cm)
# - Time step count
# - Erosion model parameters (deterministic or stochastic)

# Nuclear Engineering Parallel:
# This is analogous to XML or YAML input decks used in OpenMC, Serpent,
# or thermal-hydraulic solvers. It separates model logic from configuration.

soap:
  size: [50, 75, 20]         # Dimensions in voxels
  voxel_resolution: 1.0     # mm per voxel, used in mass calculations only
  geometry: 'cuboid'        # Options: cuboid, ellipsoid, cylinder, rounded_cuboid

simulation:
  steps: 100
  log_interval: 10
  heat_map: true
  debug_vectors: true

erosion_model:
  type: stochastic       # Options: deterministic, stochastic
  flow_vector: [0.577, 0.577, -0.577]   # Direction of water flow
  erosion_rate: 0.5         # mm^3 per step per exposed voxel
  water_source_height: 1.0

  # For stochastic model:
  erosion_std: 0.1
  erosion_fraction: 0.95 # fraction of the surface voxels that are eroded at each timestep.
  seed: 43
